### ISSUE TITLE
Anti-DDM, it hurts.

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_pir#2]
As the role is a mercenary, then you should do so if the contract picks up an innocent player, then the pirates become innocent and Vice versa, as otherwise the pirates can kill any player and they will be nothing for karma.

**Comment by lebroomer** [comment]
If an innocent picks up the contract, the pirate already gets member of the innocent team.

**Comment by Histalek** [comment]
but in what Team is the Pirate BEFORE his Contract is picked up? i think dok441 has the problem that the Pirate can just troll by shooting/killing anyone without loosing karma because he is in his own team.

**Comment by lebroomer** [comment]
Before anyone has picked up the contract, he is in TEAM_PIRATE an independent team, which can't win alone unless you activated "ttt_pir_win_alone"

**Comment by TimGoll** [comment]
yes, but he gets no karma penalty for killing other players.

**Comment by dok441** [comment]
So it does not punish the system of karma, this is the problem.

**Comment by lebroomer** [comment]
So, how is this managed for the Unknown? Never played with the role, but he should have the same problem right?

**Comment by dok441** [comment]
Yes, he has the same problem.

**Comment by TimGoll** [comment]
Actually I see no real problem here. The pirate can kill everybody if he wants to. But he has no benefit by doing so because he can't win. We could introduce a karma penalty, yes. But I see no reason for random killing as a pirate in the first place

**Comment by dok441** [comment]
Many beginners, they will kill all or people who will do it, I think it's better to close loop holes than to produce them.

**Comment by TimGoll** [comment]
I see problems in both solutions, so maybe a few other players should join the discussion

**Comment by lebroomer** [comment]
So then, appearently this is a general problem with Roles with an own Team, who have no native wincodition. Thus, there is no easy way to handle this at the moment. since the karma system is quite encapsulated from the roles, if I'm not wrong.

**Comment by ghost** [comment]
If someone kills anyone they aren't supposed to that should effect their karma in my opinion.
So if a neutral kills anyone that should effect their karma.
Karma should discourage random killing.
