### ISSUE TITLE
only Normal Pirate

### ISSUE THREAD

**Issue by hofq** [TTT-2/ttt2-role_pir#3]
in Ulx both in forcing and in the gameplay settings only the normal pirate but not the captain is displayed to me

**Comment by TimGoll** [comment]
Funny timing. I just talked with LeBroomer about this!

**Comment by hofq** [comment]
Lol

**Comment by lebroomer** [comment]
Yeah this is intended, since a Pirate Captain is a non selectable role. But ofc the first forced Pirate should get a captain, which I fixed here: https://github.com/TTT-2/ttt2-role_pir/commit/39c09dfb8f4bda835a6f6696f9df7a7fbe482d51
