### ISSUE TITLE
Wrog interaction with Amnesiac

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2-role_pir#4]
![image](https://user-images.githubusercontent.com/36534723/77699893-82a67e80-6fb3-11ea-91f5-cde677265f42.png)
[ERROR] addons/ttt2-role_pir-master/gamemodes/terrortown/entities/weapons/weapon_ttt2_contract.lua:183: attempt to index local 'masterTeamData' (a nil value)
  1. func - addons/ttt2-role_pir-master/gamemodes/terrortown/entities/weapons/weapon_ttt2_contract.lua:183
   2. unknown - lua/includes/extensions/net.lua:32

When a pirate give a contract to an Amnesiac this happens in the console

**Comment by TimGoll** [comment]
@lebroomer The amnesiac is a role without a team, just fyi

**Comment by ThePlatinumGhost** [comment]
UPDATE 
Also the unknown is affected by this bug
if the pirate give the contract to an unknown this happend
